site_name: VestibularPlatform
nav:
    - Home: index.md
    - Main platform:
        - Components: platform/components.md
        - Assembly: platform/assembly.md
    - Electrical setup and configuration: 
        - Connections: wiring/wiring.md
        - Driver configuration: wiring/config.md 
    - Optical motion sensors, option 1, ADNS-2610:
        - Components: sensors/components.md
        - Assembly: sensors/assembly.md
        - Characterization: sensors/characterization.md 
    - Optical motion sensors, option 2, ADNS-3050:
        - Components: sensors_3050/components.md
        - Assembly: sensors_3050/assembly.md
        - Characterization: sensors_3050/characterization.md
    - Optical motion sensors, option 3, PMW3360:
        - Components: sensors_3360/components.md 
    - Instrument ring and head-holder:
        - Components: holders/components.md
        - Head-plate: holders/headclamp.md
        - Assembly: holders/assembly.md 
    - Pupil Camera:
        - Components: pupil/components.md
        - Assembly: pupil/assembly.md
    - Embedded screens:
        - Components: screens/components.md
        - Assembly: screens/assembly.md
        - Virtual Reality: screens/VR.md
    - Characterization and software:
        - Platform characterization: characterization/characterization.md
        - Software: characterization/requirements.md
theme: readthedocs
markdown_extensions:
  - admonition